### ISSUE TITLE
explanation of term "n-gram"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#10]
Please explain the term above.

**Comment by jan-christiansen** [comment]
Please add the result to the wiki. You don't have to add a separate page for this result you can as well create an article with short texts about terminology.

**Comment by MadeInGer** [comment]
I've created an wiki article at https://github.com/sagr4019/ResearchProject/wiki/N-gram.

**Comment by jan-christiansen** [comment]
Please add a page with general text processing approaches and reference this article.

**Comment by MadeInGer** [comment]
An article has been created at https://github.com/sagr4019/ResearchProject/wiki/Text-Processing.
The article has also been added to the sidebar.
