### ISSUE TITLE
Optimize Code Generator: Valid programs only

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#100]
Ensure that the code generator generates valid programs only. E. g. `while -20 do ...` isn't valid. This can be done by introducing some kind of type system.

**Comment by jan-christiansen** [comment]
As discussed in the meeting, at least in the example above, we could as well change adapt the semantics of our language. For example, we could interpret `-20` as true. You just should be aware of this additional option.

**Comment by MadeInGer** [comment]
@jan-christiansen currently there are some constraints for the code generated as you can see in the readme at https://github.com/sagr4019/ResearchProject/blob/master/data-generation-and-validation/security-type-system/README.md e. g.:

- conditions contain identifier on the left side, right side is either an identifier or a number, e. g. `x<y`, `x==y`, `x<2`, `x==2`


Questions:
1. Do you think this is sufficient? This make it impossible to generate commands such as `while -20 do ...`.
2. How far do we have to go to generate "valid programs only"? Should we make sure that no variables are used before they are introduced?

**Comment by Zermy** [comment]
Hey @MadeInGer ,

today i had a meeting with the other teammates. 

In this meeting we found a optimization.
For the feature operating it would be nice that the condition always be split in to three parts
For example:
```[{'ConcatCMD': [[{'WhileCMD': [{'Condition': '**p < j'**},
                               {'Do': [{'ConcatCMD': [[{'WhileCMD': [{'Condition': **'N '
                                                                                   '< '
                                                                                   'w'},**
                                                                     {'Do': [{'IfCMD': [{'Condition': 'y '
                                                                                                      '< '
                                                                                                      '-69'},
                                                                                        {'Then': [{'AssignCMD': [[{'LiteralStr': 'a'}],
                                                                                                                 {'LiteralInt': '49'}]}]},
                                                                                        {'Else': [{'AssignCMD': [[{'LiteralStr': 'B'}],
                                                                                                                 {'LiteralInt': '44'}]}]}]}]}]}],
```
Maybe we can meet and clarify if its possible.

**Comment by DanielEggelmann** [comment]
#105 
- conditions need to include identifier node from the referenced ticket in place of strings for variablenames
- create operator nodes instead of strings
- use LiteralInt in conditions where integers are used

for example:
```
{'Condition': 
      'o ',
      '== '
      '11'
}

{'Condition': 
      {'Idenfitier' : {'Value' : 'o', 'SClass', 'H'}},
      {'Operator' : '== '},
      {'LiteralInt' : '11'}
}

{'Condition': 
      'o ',
      '== '
      'x'
}

{'Condition': 
      {'Idenfitier' : {'Value' : 'o', 'SClass', 'H'}},
      {'Operator' : '== '},
      {'Idenfitier' : {'Value' : 'x', 'SClass', 'H'}}
}
```

**Comment by DanielEggelmann** [comment]
While working on the security checking script two more thoughts came up, what could be improved with the code generation:
- For if and while just replace "Condition", "Then", "Else" and "Do" with their respective nodes. The meaning can then be determined by the order, e.g. the first node is the condition, the second the then and so on.
- For conditions use "EqualExpr" and "LessExpr" instead of the suggested above.

Examples:
```
{"AssignCMD": [{'Identifier': {'Value': 'o', 'SClass': 'H'}}, {"AddExpr": [{"LiteralInt": "1"}, {"LiteralInt": "1"}]}]}

{"AssignCMD": [{'Identifier': {'Value': 'b', 'SClass': 'H'}}, {
        "AddExpr": [{"SubExpr": [{"LiteralInt": "4"}, {"Identifier": {"Value": "a", "SClass": "H"}}]},
                    {"LiteralInt": "2"}]}]}

{"IfCMD": [{"LessExpr": [{"Identifier": {"Value": "a", "SClass": "H"}}, {"LiteralInt": "4"}]}, ...]}

{"WhileCMD": [{"EqualExpr": [{"Identifier": {"Value": "x", "SClass": "H"}}, {"LiteralInt": "3"}]}, ...]}
```

**Comment by jan-christiansen** [comment]
As discussed in the meeting I will close this issue and create new ones for the refactorings we discussed.
