### ISSUE TITLE
Get overview about code generator implementation

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#101]
Get an overview about the code generator from @MadeInGer, which is available [here](https://github.com/sagr4019/ResearchProject/tree/master/Examples/Datagen%20for%20a%20sound%20type%20system/MadeInGer).

**Comment by Zermy** [comment]
I got an overview. On Thursday Marcel and I had a meeting and  discussed further steps . For this steps extra issues are created.
