### ISSUE TITLE
Security class syntax concept

### ISSUE THREAD

**Issue by DanielEggelmann** [sagr4019/ResearchProject#104]
Create a concept to integrate the security classes into the syntax of the language defined in the paper.

**Comment by DanielEggelmann** [comment]
Added wiki page:
https://github.com/sagr4019/ResearchProject/wiki/Security-class-syntax---%22A-Sound-Type-System-for-Secure-Flow-Analysis%22

**Comment by jan-christiansen** [comment]
I would like to record this kind of end result in a latex file. Please adapt the BNF in the latex file when #107 is finished and remove the wiki article.

**Comment by jan-christiansen** [comment]
Obsolete
