### ISSUE TITLE
Create basic latex document

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#106]
I would like to record at least some of the results in a latex document. Create a very basic file using the [LNCS style file](https://www.springer.com/de/it-informatik/lncs/conference-proceedings-guidelines) under the link named "LaTeX2e Proceedings Templates (zip)". For example, I would like to record the grammar that we used to generate examples in the latex file.

**Comment by sagr4019** [comment]
done. I have send you a link per email

**Comment by jan-christiansen** [comment]
There are multiple problems with the latex file.

- It does not compile because `amsmath` has to be imported before `semantic` [see here](https://tex.stackexchange.com/questions/375992/bad-mathchar-with-semantic-package).
- Why do you use `\'{}` in the grammar? This command adds an accent on top of a character [see here](https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Escaped_codes).

**Comment by sagr4019** [comment]
I use \'{} in the grammar to indicate that's not the same element in a formular. For Example e+**e'**

**Comment by jan-christiansen** [comment]
@sagr4019 What is the status of this issue?

**Comment by sagr4019** [comment]
@jan-christiansen Sorry! Is in review now
