### ISSUE TITLE
Grammar for programs in latex file

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#107]
Look for a library for writing BNFs in latex. Use the library for writing down the grammar from "A Sound Type System for Secure Flow Analysis" in the latex file. We will later adapt this grammar to our needs.

This issue is blocked by #106.

**Comment by MadeInGer** [comment]
My first attempt to write down our current grammar in BNF:
 
```
(integers)      int ::= [0-9]+
(variables)     var ::= [a-zA-Z]+
(literals)      lit ::= int | var
(expressions)   exp ::= lit | exp + exp' | exp - exp' | exp = exp' | exp < exp'
(commands_tmp)  c_t ::= var := exp | c_t; c_t | "while" exp "do" c_t | "if" exp "then" c_t "else" c_t'
(preassign)     pre ::= var := "Null"
(commands)      cmd ::= c_t | for var in c_t do pre; c_t
```

**Comment by jan-christiansen** [comment]
- `preassign` must be replaced with `declaration`
- the `for` in the definition of `commands` is not allowed

**Comment by MadeInGer** [comment]
The issue #102 will be used for further discussions regarding our BNF notation.
