### ISSUE TITLE
Implement pretty printer for AST

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#109]
A pretty printer generates a human readable version of an AST with correct bracketing.

**Comment by MadeInGer** [comment]
Done in https://github.com/sagr4019/ResearchProject/commit/0a877910207f74aaf39ead367f0dd6f34955b60c. Examples are available [here](https://github.com/sagr4019/ResearchProject/blob/master/data-generation-and-validation/security-type-system/examples.txt).

**Comment by jan-christiansen** [comment]
I would guess that there is some form of string formatting/string interpolation for improving the code.

**Comment by jan-christiansen** [comment]
I would guess that there is some form of string formatting/string interpolation for improving the code.
