### ISSUE TITLE
Refactor generation of expressions

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#110]
The generator should generate arbitrary expressions, for example, as condition of a `while` or `if`. Don't bother about type correctness , that is, simply generate expressions like `(x < y) + z`. Restrict the depth of expressions that are generated.

**Comment by MadeInGer** [comment]
Done in https://github.com/sagr4019/ResearchProject/commit/0a877910207f74aaf39ead367f0dd6f34955b60c. Examples are available [here](https://github.com/sagr4019/ResearchProject/blob/master/data-generation-and-validation/security-type-system/examples.txt).

**Comment by MadeInGer** [comment]
Some of my notes from the meeting:
- use classes instead of functions, e. g. class VarGenerator, ExpressionGenerator, CommandGenerator (...) that contain only one function 'gen'
- gen should return ast dictionary instead of storing it in class variable 'ast'
- remove class variable 'ast'
- implement pseudo randomness by implementing a seed

**Comment by MadeInGer** [comment]
According to the rules used in the paper, an expression can only consists of an odd number of expressions. For the case that an even number has been generated, the next higher odd number is selected.

**Comment by MadeInGer** [comment]
Notes of the last meeting:
- Each `gen`-function shouldn't take arguments that include expressions/commands. Instead it should return an object of the respective class and generate it without arguments.
- Recursion functions should decrement the `max_count` variable at the beginning of the function. As soon as the variable is 0, it should return itself.
- Implement a (probably global) list to save all assignments that can be used for all commands. This should ensure that e. g. `if`-commands only use assigned variables in the condition. As a result we should easier generate valid code.
- According to the grammar used in the paper, a phrase is either an expression or a command. To avoid the generation of code fragments which only consist of an expression as programs (e. g. a variable or an integer), we should remove phrases from our grammar and use command(s) to generate code fragments, as commands represent programs.

There may be additional points to be added once the ticket #121 has been closed.

@jan-christiansen please edit this post (if needed) and move the ticket to the To Do-column as soon as you're done.

**Comment by MadeInGer** [comment]
A few examples with different depths are available in the directory [programs](https://github.com/sagr4019/ResearchProject/tree/master/data-generation-and-validation/security-type-system/programs).

**Comment by MadeInGer** [comment]
https://github.com/sagr4019/ResearchProject/commit/6e7063f8f6ab36f3b1c6b0d24b4ed867d7af04b2 now prevents the generation of reserved keywords as variables.
