### ISSUE TITLE
Read section "A Formal Treatment of the Type System"

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#112]
Write down questions that arise from reading the text.

**Comment by Salvos** [comment]
1. how de we represent a compose in code?
2. how could i imagine the "location type"`?
3. Should we use subtypes and the rules for these? And if yes: do we have a good example for it?

**Comment by Salvos** [comment]
Just as a note for the upcoming meeting:
<br>
Lattice order on security levels (Subtyping):
- https://slideplayer.com/slide/8955430/27/images/29/An+Example+Security+Lattice.jpg
- http://kastner.ucsd.edu/wp-content/uploads/2014/07/admin/lattice.jpg
<br>
Presentation slides:

- http://people.cs.ksu.edu/~tamtoft/890/10Fall/JasonVolSmiIrv.pdf
- https://www.cs.cornell.edu/andru/cs711/2003fa/presentations/vsi96-slides.pdf
