### ISSUE TITLE
explanation of term "sequence embedding"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#12]
Please explain the term above.

**Comment by Zermy** [comment]
Wiki page created.

**Comment by Zermy** [comment]
Dont find more informations about sequence embedding. There is no other meaning as 
sequence processing.

**Comment by jan-christiansen** [comment]
See [Article](../wiki/sequence-embedding).

**Comment by Zermy** [comment]
Hey Jan, i hope i got it now. Let me know if its right. So i will update my wiki article.

One approach to representing programming code and programs is "sequential embedding". In neural networks, data is realized in vectors or matrices. Program code is therefore stored as a "string" in vectors. In order not to reserve the memory unnecessarily, it is attempted to select the vector / template size such that each field is filled with parts of program code or sequences. 
The selected data can be seen as a projection of a vector space. From this vector space results the context and possible program sequences. The field that has been selected will be surrounded by matching operations or code characters and can be used to compile possible functioning programs.

**Comment by Zermy** [comment]
[See article](https://github.com/sagr4019/ResearchProject/wiki/sequence-embedding/)

**Comment by jan-christiansen** [comment]
@Zermy Please let's meet and talk about the article.

**Comment by Zermy** [comment]
Text restructured, stuck on the discribtion of the One-Hot function
