### ISSUE TITLE
Rework the "security type check"-script for secure type system

### ISSUE THREAD

**Issue by Salvos** [sagr4019/ResearchProject#125]
- [x] Change ```identifierStorage```-style to key-value pairs ```("temp" : "H", "temp2" : "L")```
- [x] Change name of ```identifierStorage``` to ```environment```
- [x] Change return value from ```(valid?, highest security class)``` to ```(resulting security class like "H var")```
- [x] Enhance "security type check" with a "best fit" conclusion type by using subtype coercion (```H cmd``` for command-types and ```L``` for the other types like ```L var```)

**Comment by jan-christiansen** [comment]
* Please also change the name `identifierStorage` to `environment`.

**Comment by Salvos** [comment]
I reworked the code - the next steps are
- change the environment-style in the codegenerator 
- run the "security type check" with example codes

**Comment by MadeInGer** [comment]
@Salvos 
- I've updated the codegenerator, but I'm getting a NoneType error. It looks like your code returns None if i check secure or non secure code.
- we do no longer have Null-Kinds. Instead we now have Declare-Kinds.
- I suppose we don't need an environment for check_rules() anymore as we have the declarations in the ast at the beginning, right?

**Comment by jan-christiansen** [comment]
The type checker simply adds entries to an initially empty type environment when processing declarations. That is, the code is extended with an additional rule for variable declarations.

**Comment by Salvos** [comment]
@MadeInGer 
I've updated the security-type-check by 
- adding the declare-kind
- providing a valid and an invalid example of secure code

We don't need the full environment dict, but we need an empty dict like ```environment = {}```, so the script add entries by itself.
We could implement a wrapper-method like "check_security(ast)" which run "check_rules(ast, environment)" with an empty environment dict, and return a boolean value of security.

**Comment by MadeInGer** [comment]
There seems to be another mistake. I added a third example, which is invalid if I am not mistaken, but the security checker outputs valid. https://github.com/sagr4019/ResearchProject/blob/8c1c57ba7a8ca501ed60f46dd593cc81d3cf3ff7/data-generation-and-validation/security-type-system/check_security.py#L170-L184

**Comment by Salvos** [comment]
> 
> 
> There seems to be another mistake. I added a third example, which is invalid if I am not mistaken, but the security checker outputs valid.
> 
> [ResearchProject/data-generation-and-validation/security-type-system/check_security.py](https://github.com/sagr4019/ResearchProject/blob/8c1c57ba7a8ca501ed60f46dd593cc81d3cf3ff7/data-generation-and-validation/security-type-system/check_security.py#L170-L184)
> 
> Lines 170 to 184 in [8c1c57b](/sagr4019/ResearchProject/commit/8c1c57ba7a8ca501ed60f46dd593cc81d3cf3ff7)
>  ```# third example, obviously invalid```
>  ```# H D;```
>  ```[...]```
>  ```# L D;```

I forgot to prevent duplicate declaration @MadeInGer.

**Comment by jan-christiansen** [comment]
Identifying duplicate declarations of variables is not a task for the type checker. A type checker always assumes that other static checks, like the check that all variables are declared, are done beforehand.

**Comment by jan-christiansen** [comment]
* See https://docs.quantifiedcode.com/python-anti-patterns/correctness/not_using_get_to_return_a_default_value_from_a_dictionary.html to improve the implementation of `get_label_from_environment`.
* Please add some examples, that test the implementation. That is, provide example programs that are not auto-generated but illustrate some aspect of the type checking.

**Comment by jan-christiansen** [comment]
The examples are much better now. Using a library for unit tests would have been a good choice.

You did not process the first bullet point.

**Comment by Salvos** [comment]
> You did not process the first bullet point.
I replaced the implementation of ```get_label_from_environment``` with ```environment.get(node.get("Name"), None)```
