### ISSUE TITLE
Refactor CodeGenerator: security labels instead of Null

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#128]
Use security labels `L`/`H` for variables instead of `Null` at the beginning of each program.

**Comment by Zermy** [comment]
@MadeInGer While testing the data generator for our conception of a conversion from AST to vector, we noticed an error. The key "kind" for a declaration is not implemented and returns none.
![image](https://user-images.githubusercontent.com/16175376/48733307-8f3df880-ec42-11e8-8d3a-c980f01a11ca.png)

maybe like this:
![image](https://user-images.githubusercontent.com/16175376/48733718-c1038f00-ec43-11e8-85b9-5fc248bd4bff.png)

Besides the check_security script returns a L or a H and you need a "true" or "false".

**Comment by jan-christiansen** [comment]
Why not simply the following?

```
{'Kind': 'Seq',
           'Left': {'Kind': 'Declare',
                    'Label': 'L',
                    'Var': 'ZjT'},
           'Right': ...
```

The declaration will never be used to declare something other than a variable.
