### ISSUE TITLE
Revise codegenerator

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#129]
Change the codegenerator as follows:
- higher probability to generate Int instead of var (by implementing a frequency function)
- feature to generate any amount of programs into directories valid/invalid

**Comment by jan-christiansen** [comment]
If the second option works fine, the first one is not required anymore.

**Comment by jan-christiansen** [comment]
The implementation of `frequency` is not correct. For example, `frequency([(1, VarExpr()), (1, IntExpr())]).gen()` would always select `VarExp`.

**Comment by jan-christiansen** [comment]
- Investigate the difference between tuples and arrays in Python
- If there is a difference, use tuples in the definition of `frequency`
- Use functions like `map` and `filter` instead of loops where possible

**Comment by MadeInGer** [comment]
Tuples are immutable, whereas lists are mutable. During the `frequency` function nothing is changed in the list we pass. So we should use tuples instead. Also the function `one_of` will be changed for the same reason.
