### ISSUE TITLE
explanation of term "multilayer perceptron"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#13]
Please explain the term above.

**Comment by Zermy** [comment]
Wiki page created

**Comment by jan-christiansen** [comment]
See [Article](../wiki/multilayer-perceptron).

**Comment by jan-christiansen** [comment]
I at least don't understand the formulas in section `Calculation` without further explanation. If you do, add an explanation. If you don't, remove the formulas.

**Comment by Zermy** [comment]
I removed the formulas.
