### ISSUE TITLE
Take a look into the existing ASTs

### ISSUE THREAD

**Issue by sagr4019** [sagr4019/ResearchProject#142]
The paper[Cross-Language Learning for Program Classification
using Bilateral Tree-Based Convolutional Neural Networks
](https://github.com/bdqnghi/bi-tbcnn) provides already generated AST files in pickle format. First we have to find more about pickle and how to use this files in a python program to display the ASTs. Afterwards we compare it to our ASTs and either modify our data structure or the AST2Vec algorithm to fit our needs

**Comment by sagr4019** [comment]
I am currently unable to deserialize the ASTs in pickle format because of a `ModuleNotFoundError: No module named 'fast_pb2\r`

**Comment by sagr4019** [comment]
Explanation of the python pickle module: 

> The pickle module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy. Pickling (and unpickling) is alternatively known as “serialization”, “marshalling,” [1] or “flattening”; however, to avoid confusion, the terms used here are “pickling” and “unpickling”.

**Comment by sagr4019** [comment]
To reproduce the "ModuleNotFoundError: No module named 'fast_pb2', clone the repository from [github](https://github.com/bdqnghi/bi-tbcnn), navigate in the folder `ast2vec` and execute `python fast_merge_pickles_to_pickle.py /path/to/ast/folder cpp output.pkl`

**Comment by jan-christiansen** [comment]
I had to install the `protobuf` package via `pip`. Afterwards, deserialising an AST worked as expected. I use python 2.7.10. If this is not working for you, please ask one of your colleagues to give it a try.

**Comment by Zermy** [comment]
I think the issue is already resolved. Therefore it can be closed. Other technical difficulties are solved in the team or another issue is opened.
