### ISSUE TITLE
How do they generate their ASTs and vectors?

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#144]
**How they generate their ASTs and Vectors**

First they crawled GitHub repositories to retrieve about 600 instances of program code that implement each algorithm in each programming language. These code snippets are parsed
into abstract syntax trees (ASTs) represented in Pickle format. Unfortunately I can't find out more about the first step, because the Bitbucket Repo is not public and there are no further details in the paper.

Then each AST node is represented in a vector.  They use an "encoding-layer", which represents the semantically same types with small distance in a vector space. The types "While" and "For" are of equal importance for this task. They are loops and have a small distance in the space spanned by the vectors.

To get structural information of the AST they use the "fixed-depth subtree filters" of Mou et al. (2016).
After reading the [paper](https://arxiv.org/abs/1409.5718) section Tree-based Convolutional Layer we are talking about a "fixed-depth window", which corresponds to the filter kernel.
![AST](https://s15.directupload.net/images/190108/jqp2xcvx.png)
The blue vectors are the pre-trained vectors of the AST nodes and now become the new orange vectors through filtering and pooling.
The filter again influences the weighting of the vector and the elements in it and defines the features of the vector. The pooling takes over the length and the position in the AST. We already had pooling in the [Wiki](https://github.com/sagr4019/ResearchProject/wiki/Pooling) it helps to combine vectors or matrices, because too long vectors slow down the learning process. In addition, the vectors learned from the network should all have the same length. The vectors that are shorter will be filled with zeros in this task. According to the work too fundamental we use a tree-way-pooling with TOP,LEFT and Right so that the AST or the position of the nodes is taken into account.

The information must be recognizable in the vectors so that conclusions can be drawn about the structure of the AST.

The formula of the filter or the feature detector:
![Formel](https://s15.directupload.net/images/190108/o4tngm73.png)
 
- y           - Summarized value of an input vector for the new output vector.
- xi          - are the values
- Wconv  - the combined weighting of a node
- B          - bias

Tanh is used to encode the features in the same vector space.

**Comment by jan-christiansen** [comment]
Revise

**Comment by Zermy** [comment]
@jan-christiansen I reworked the ticket. I'm not 100% sure about the formula and the value of the new feature.

**Comment by Zermy** [comment]
In the triangle, the color of a pixel is a combination of three primary colors; in the convolution process, the weight for a node is a combination of three weight parameters, namely Wtconv, Wlconv, and Wrconv (t top, l left, r right).

**Comment by jan-christiansen** [comment]
The text is okay. Some comments:

> The blue vectors are the pre-trained vectors of the AST nodes and now become the new orange vectors through filtering and pooling.

The picture depicts the convolution only.

> The pooling takes over the length and the position in the AST.

Here it is not clear, the length of what you are referring to.
