### ISSUE TITLE
Check securitychecker

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#145]
The securitychecker outputs `None` for a valid program:
```
L c; 
L V; 
L U; 
L z; 
L Q; 
L d; 
L G; 
L Z; 
H B; 
L K; 
H u; 
L q; 
L i; 
L g; 
H Y; 
L n; 
L L; 
L e; 
L y; 
if ((R < r) < (R - O)) then {
    if (J + M) then {
        if b then {
            Q := ((V + Z) - (G - n))
        } else {
            i := ((K + y) < (G - U))
        }
    } else {
        if (t - y) then {
            Y := ((-332565 < u) - (d + B))
        } else {
            z := (g - c)
        }
    }
} else {
    if (t == j) then {
        q := y
    } else {
        e := (d == L)
    }
}
```

AST:

`{'Left': {'Var': 'c', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'V', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'U', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'z', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'Q', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'd', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'G', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'Z', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'B', 'Kind': 'Declare', 'Label': 'H'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'K', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'u', 'Kind': 'Declare', 'Label': 'H'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'q', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'i', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'g', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'Y', 'Kind': 'Declare', 'Label': 'H'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'n', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'L', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'e', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Left': {'Var': 'y', 'Kind': 'Declare', 'Label': 'L'}, 'Kind': 'Seq', 'Right': {'Kind': 'If', 'Condition': {'Left': {'Left': {'Name': 'R', 'Kind': 'Var'}, 'Kind': 'Less', 'Right': {'Name': 'r', 'Kind': 'Var'}}, 'Kind': 'Less', 'Right': {'Left': {'Name': 'R', 'Kind': 'Var'}, 'Kind': 'Sub', 'Right': {'Name': 'O', 'Kind': 'Var'}}}, 'Else': {'Kind': 'If', 'Condition': {'Left': {'Name': 't', 'Kind': 'Var'}, 'Kind': 'Equal', 'Right': {'Name': 'j', 'Kind': 'Var'}}, 'Else': {'Left': {'Name': 'e', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Left': {'Name': 'd', 'Kind': 'Var'}, 'Kind': 'Equal', 'Right': {'Name': 'L', 'Kind': 'Var'}}}, 'Then': {'Left': {'Name': 'q', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Name': 'y', 'Kind': 'Var'}}}, 'Then': {'Kind': 'If', 'Condition': {'Left': {'Name': 'J', 'Kind': 'Var'}, 'Kind': 'Add', 'Right': {'Name': 'M', 'Kind': 'Var'}}, 'Else': {'Kind': 'If', 'Condition': {'Left': {'Name': 't', 'Kind': 'Var'}, 'Kind': 'Sub', 'Right': {'Name': 'y', 'Kind': 'Var'}}, 'Else': {'Left': {'Name': 'z', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Left': {'Name': 'g', 'Kind': 'Var'}, 'Kind': 'Sub', 'Right': {'Name': 'c', 'Kind': 'Var'}}}, 'Then': {'Left': {'Name': 'Y', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Left': {'Left': {'Kind': 'Int', 'Value': -332565}, 'Kind': 'Less', 'Right': {'Name': 'u', 'Kind': 'Var'}}, 'Kind': 'Sub', 'Right': {'Left': {'Name': 'd', 'Kind': 'Var'}, 'Kind': 'Add', 'Right': {'Name': 'B', 'Kind': 'Var'}}}}}, 'Then': {'Kind': 'If', 'Condition': {'Name': 'b', 'Kind': 'Var'}, 'Else': {'Left': {'Name': 'i', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Left': {'Left': {'Name': 'K', 'Kind': 'Var'}, 'Kind': 'Add', 'Right': {'Name': 'y', 'Kind': 'Var'}}, 'Kind': 'Less', 'Right': {'Left': {'Name': 'G', 'Kind': 'Var'}, 'Kind': 'Sub', 'Right': {'Name': 'U', 'Kind': 'Var'}}}}, 'Then': {'Left': {'Name': 'Q', 'Kind': 'Var'}, 'Kind': 'Assign', 'Right': {'Left': {'Left': {'Name': 'V', 'Kind': 'Var'}, 'Kind': 'Add', 'Right': {'Name': 'Z', 'Kind': 'Var'}}, 'Kind': 'Sub', 'Right': {'Left': {'Name': 'G', 'Kind': 'Var'}, 'Kind': 'Sub', 'Right': {'Name': 'n', 'Kind': 'Var'}}}}}}}}}}}}}}}}}}}}}}}}}}`

**Comment by jan-christiansen** [comment]
Why is this issue closed? Is the problem solved?

**Comment by MadeInGer** [comment]
Yes, it's solved. I'm revising the generation of valid/invalid programs since a few days and I noticed that I only added labels for vars that has been used in assignments. 

Therefore e. g. `J` and `M` from `if (J + M) then {` are not declared with labels and the securitychecker outputs None, which is ok.
