### ISSUE TITLE
Fix code and train net

### ISSUE THREAD

**Issue by Salvos** [sagr4019/ResearchProject#150]
The [run file](https://github.com/bdqnghi/bi-tbcnn/blob/master/run) in the root-dir of the project, perform the following commands:

```	
mkdir -p vec
chmod a+w vec
ast2vec/run
```

The given '[ast2vec/run](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/run)'-script fails to execute [ast2vec/ast2vec/fast_picke_to_nodes.py](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/ast2vec/fast_pickle_file_to_nodes.py) and [ast2vec/ast2vec/train.py](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/ast2vec/train.py)

- [x] Fix the incorrect code in [ast2vec/ast2vec/fast_picke_to_nodes.py](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/ast2vec/fast_pickle_file_to_nodes.py) to run this program without errors
- [x] If necessary: Fix the incorrect code in [ast2vec/ast2vec/train.py](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/ast2vec/train.py)
- [x] Run [ast2vec/ast2vec/train.py](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/ast2vec/train.py)

**Comment by Salvos** [comment]
I talked to @sagr4019 and he fixed the code by editing the '[ast2vec/run](https://github.com/bdqnghi/bi-tbcnn/blob/master/ast2vec/run)'-script. I tried to fix and execute the code but both of my Ubuntu-VMs are constantly freezing after execute the 'fix'. 

The fix contains the following two changes: 

Change line 10 to: 
```python3 ast2vec/ast2vec/map3.py input/maps.$language.pkl maps.$language.pa```
(change the folder of the output maps-file from ```ast2vec/``` to ```/```)

Change line 11 to: 
```python2 ast2vec/ast2vec/fast_pickle_file_to_nodes.py vec/fast_algorithms.$language.pkl vec/fast_algorithms_nodes_$language.pkl```
(change the ```_``` to ```.``` before $language)

**Comment by jan-christiansen** [comment]
If your python implementation freezes and @sagr4019 does not, what is the difference between your environments, for example, python version, library versions.

**Comment by sagr4019** [comment]
@Salvos  please use this "new" run script and place it in the folder ast2vec where the old run file is located.
Beside that, please make the following changes in the `file fast_pickle_file_to_nodes.py`. 
Replace:
`map_filename = 'maps%s.pa' % lang` with:
```
    lang="java"
    vec_path = os.path.dirname(basename)
    map_filename = 'maps%s.pa' % lang
    map_filename = os.path.join(vec_path,map_filename)
```
```
#!/bin/bash
cd ..
ROOT_DIR=${PWD}
echo "Working directory is: $ROOT_DIR"
language=java
echo "Language is: $language"
mkdir -p $ROOT_DIR/vec
python2 $ROOT_DIR/ast2vec/ast2vec/fast_merge_pickles_to_pickle.py $ROOT_DIR/ast $language $ROOT_DIR/vec/fast_algorithms_$language.pkl
python3 $ROOT_DIR/ast2vec/ast2vec/map3.py $ROOT_DIR/input/maps.$language.pkl $ROOT_DIR/vec/maps$language.pa
python2 $ROOT_DIR/ast2vec/ast2vec/fast_pickle_file_to_nodes.py $ROOT_DIR/vec/fast_algorithms_$language.pkl $ROOT_DIR/vec/fast_algorithms_nodes_$language.pkl
python2 $ROOT_DIR/ast2vec/ast2vec/train.py $ROOT_DIR/vec/fast_algorithms_nodes_$language.pkl $ROOT_DIR/vec/fast_pretrained_vectors_$language.pkl
python2 $ROOT_DIR/ast2vec/ast2vec/fast_pickle_file_to_training_trees.py $ROOT_DIR/vec/fast_algorithms_$language.pkl $ROOT_DIR/vec/fast_algorithms_trees_$language.pkl
```

Python 3 Package:
`pyarrow (0.11.1)`

Python 2 Package:
```
scikit-learn (0.20.1)
tensorflow (1.12.0)
protobuf (3.6.1)
```

Script runs successfully on  Ubuntu 18.04.1 LTS

**Comment by Salvos** [comment]
As discussed on Wednesday I limited the examples (for now to 10 per algorithm). 
Now the [script of @sagr4019](https://github.com/sagr4019/ResearchProject/issues/150#issuecomment-449090472) runs on my VM with less power without problems.
