### ISSUE TITLE
How can you handle values in an AST?

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#158]
Are there other works that provide examples of how to deal with values in ASTs?
How could we do this in our task?

**Comment by Zermy** [comment]
I found an example of how a function is represented in an AST. The values of the variables are also represented. The question is, we don't need the value of the variable but only the one that exists and which SecurityType it has. [Chapter6.6](https://www3.nd.edu/~dthain/courses/cse40243/fall2016/chapter6.pdf)

I'm still searching for more possibilities.

**Comment by jan-christiansen** [comment]
Please note that we are not interested in representing something in an AST. We are interested in mapping ASTs with values into vectors.

**Comment by Zermy** [comment]
An explicit example where the analysis of the network aims to check a result of variables was not found. The value of the variable is often negligible. Therefore, I will not search any further here. If by chance something else results, I will share this knowledge.
