### ISSUE TITLE
Double int assigned in main.py

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#159]
In line 15 in main.py we assigned `18` to both `-` and `a`. I assume that this affected our trainings, so we should fix that and retrain? https://github.com/sagr4019/ResearchProject/blob/de4e9870b0b5bd81069a15c5628c2bb2ea4d6e75/final-code/team-2/main.py#L15

**Comment by DanielEggelmann** [comment]
Should be fixed now.
