### ISSUE TITLE
explanation of term "long short-term memory networks (LSTM)"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#16]
Please explain the term above.

**Comment by DanielEggelmann** [comment]
Added wiki page
https://github.com/sagr4019/ResearchProject/wiki/Long-short-term-memory-networks

**Comment by jan-christiansen** [comment]
Please add an article that collects different forms of neural networks.

**Comment by DanielEggelmann** [comment]
Added wiki page for for neural network types:
https://github.com/sagr4019/ResearchProject/wiki/Neural-network-types

**Comment by jan-christiansen** [comment]
Please move the issue to "Ready for Review", if it is ready for review.
