### ISSUE TITLE
explanation of term "logistic regression"

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#17]
Available at https://github.com/sagr4019/ResearchProject/wiki/Logistic-regression

**Comment by jan-christiansen** [comment]
Please add an article that collects approaches from the area of machine learning, that do not use neural networks. Also add a short statement to the overview which problem is solved with the approach (for example, classification of data).

**Comment by MadeInGer** [comment]
The article has been created at https://github.com/sagr4019/ResearchProject/wiki/Machine-Learning-(specific). It is also available in our sidebar.
