### ISSUE TITLE
explanation of term "hyperparameter"

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#18]
Available at https://github.com/sagr4019/ResearchProject/wiki/Hyperparameter

**Comment by jan-christiansen** [comment]
Please move the text about hyper parameters to an article about general terminology.

**Comment by MadeInGer** [comment]
The text has been moved to https://github.com/sagr4019/ResearchProject/wiki/General-Terminology, also available in our sidebar.
