### ISSUE TITLE
 explanation of term "Sentiment analysis"

### ISSUE THREAD

**Issue by Salvos** [sagr4019/ResearchProject#19]
Also known as "opinion mining" the sentiment analysis is part of the text analysis. This automatism tries to figure out which subjective impressions are present in a text (e.g. attitudes, emotions or opinions like 'i hate red cars'). To improve this, the automatism, it recieve data from NLP, statistics or some machine learning methods.

It can be used to get subjective data for questions like: "Why aren't customers buying our Product?"

**Comment by jan-christiansen** [comment]
Please add your results to the wiki and add a comment here that you have written the text. An issue is only used to organise work.

**Comment by jan-christiansen** [comment]
Please state what the input and what the output of the analysis is and provide one approach that is used to solve this kind of problem.
