### ISSUE TITLE
Information about "Boltzmann machine"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#26]

**Comment by Zermy** [comment]
Done. See wiki article.

**Comment by jan-christiansen** [comment]
Please reference the article here.

**Comment by jan-christiansen** [comment]
The link ist stell missing.

**Comment by Zermy** [comment]
[See Wiki ](https://github.com/sagr4019/ResearchProject/wiki/Bolzmann-Machine)

**Comment by Zermy** [comment]
updated.
I will add a refercene for hopfield networks.
