### ISSUE TITLE
Research neural network frameworks

### ISSUE THREAD

**Issue by DanielEggelmann** [sagr4019/ResearchProject#28]
Research neural network frameworks.

**Comment by DanielEggelmann** [comment]
Added wiki page:
https://github.com/sagr4019/ResearchProject/wiki/Overview-(Frameworks)

**Comment by Zermy** [comment]
Deep Learning Frameworks from Nvidia.
https://developer.nvidia.com/deep-learning-frameworks

**Comment by jan-christiansen** [comment]
As a first step we will try Tensorflow and Keras.
