### ISSUE TITLE
Unsupervised vs. supervised learning

### ISSUE THREAD

**Issue by Salvos** [sagr4019/ResearchProject#33]

**Comment by Salvos** [comment]
Added wiki page
https://github.com/sagr4019/ResearchProject/wiki/Unsupervised-vs.-supervised-learning

**Comment by jan-christiansen** [comment]
* Please check the statement "Typically problems the supervised learning have are "classification" and "regression".".
* Provide one concrete example for both approaches.

**Comment by Salvos** [comment]
- Corrected the given statement
- Added a graphic example for the given examples

**Comment by jan-christiansen** [comment]
These are not good examples as they are still very abstract. Nevertheless, I will close this issue.

**Comment by jan-christiansen** [comment]
The examples are very unspecific. For example, a specific example would state how one specifies similarity in order to classify data. In order to be this specific the examples have to use a specific machine learning approach.
