### ISSUE TITLE
Collect tasks to solve with neural network

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#35]
https://gormanalysis.com/neural-networks-a-worked-example/

**Comment by jan-christiansen** [comment]
This issue is supposed to collect tasks that we can use as a first example for testing different neural network frameworks. When we have agreed upon a task we will try to solve this task with TensorFlow and Keras.

**Comment by jan-christiansen** [comment]
We have already implemented some simple examples.
