### ISSUE TITLE
Read Related Work: Convolutional Neural Networks over Tree Structures for Programming Language Processing

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#37]
Paper : Convolutional Neural Networks over Tree Structures for Programming Language Processing 
http://sei.pku.edu.cn/~zhanglu/Download/AAAI16.pdf

**Comment by Zermy** [comment]
Moved to Backlog. Frist we try to reproduce the "Toy Language" project. Then we may devote ourselves to other types of networks.
