### ISSUE TITLE
Read Related Work: Learning a Static Analyzer: A Case Study on a Toy Language

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#38]
Paper : LEARNING A STATIC ANALYZER: A CASE STUDY ON A TOY LANGUAGE https://openreview.net/pdf?id=ry54RWtxx
Paper : Reports https://openreview.net/forum?id=ry54RWtxx

**Comment by Zermy** [comment]
[See Article](https://github.com/sagr4019/ResearchProject/wiki/Summary-of-%22TOY-LANGUAGE%22)

**Comment by jan-christiansen** [comment]
Duplicate of #41
