### ISSUE TITLE
Data generation for paper "LEARNING A STATIC ANALYZER: A CASE STUDY ON A TOY LANGUAGE"

### ISSUE THREAD

**Issue by sagr4019** [sagr4019/ResearchProject#40]
added first version to git
[data_generation.py](https://github.com/sagr4019/ResearchProject/blob/master/Examples/TensorFlow/data_generation.py)

**Comment by MadeInGer** [comment]
A modified version of data_generation.py and a first version of data_validator.py has been added along with some examples.

**Comment by jan-christiansen** [comment]
Please write a short article how the program generates data and how it is used.

**Comment by MadeInGer** [comment]
An article has been started at https://github.com/sagr4019/ResearchProject/wiki/Data-generation-and-validation

**Comment by jan-christiansen** [comment]
Why is the source code in a directory named `TensorFlow`?

**Comment by MadeInGer** [comment]
The source code has been moved into the Examples directory.
