### ISSUE TITLE
Search for scientific papers that are related to "LEARNING A STATIC ANALYZER: A CASE STUDY ON A TOY LANGUAGE"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#43]
Searching with https://scholar.google.de for related Papers and analyze them.

**Comment by Zermy** [comment]
No matching results found. Consultation tomorrow at the meeting.

**Comment by MadeInGer** [comment]
Just found a related paper. Maybe we should give it a try.
https://peerj.com/preprints/3123.pdf

Source code is available at https://peerj.com/preprints/3123/ (bottom of the page)

**Comment by jan-christiansen** [comment]
This looks interesting. Please add an issue to investigate how the implementation is working in comparison to our current implementation. Please also add an issue to write a summary of the paper.
