### ISSUE TITLE
Recheck our "Toy Language" experiment (code) to find errors / suggest improvements

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#47]
The goal is to understand the code [(issue here)](https://github.com/sagr4019/ResearchProject/issues/42) regarding the first experiments of the toy language neural network implementation in more detail than in the meeting and to find out what can be improved.

**Comment by MadeInGer** [comment]
The code looks plausible from our point of view. We can not discover any mistakes in the code, so we have to solve the problem differently.

**Comment by jan-christiansen** [comment]
In fact, the implementation does not even make correct use of tokens.
