### ISSUE TITLE
ID3

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#5]
Find  more about the ID3 Learning algorithm

**Comment by Zermy** [comment]
ID3 builds in the year 1986 used to analyse big data in decision trees. The algorithm tends to overfit, herefor the test data adjusts perfectly without any generalizing deviations. New data with more fexibility would be recognised worse in addition the error rate raised.

**Comment by Zermy** [comment]
The ID3- Algorithm is fundamental and builds a structure for many other algorithms. Don’t underestimate its effect and performance.
It is easy to break it down in three essential steps.
Step 1:
Select an attribute with the highest profit of information. Observe all the features of the database and chose between the best classified data’s.
Step 2:
Apply the junction with the feature. If the results are under the section (1unique value), definitely save the intersection and go back
Step 3: 
Recursive continuation for this process. Otherwise break down the data corresponding with subsets in context with the attributes. At last repeat these steps for every subset.

**Comment by jan-christiansen** [comment]
Please add a short text about ID3 to the wiki.

**Comment by jan-christiansen** [comment]
In the future, please always add a link to the article here.

The article is not as clear as it could be but as we will probably not use the algorithm in the near future it is OK for now. I like the links to the additional resources.
