### ISSUE TITLE
Try to contact  the authors of " TOY LANGUAGE" for open issues or more details

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#51]
- Summary of all questions
- Contact via E-Mail

**Comment by Zermy** [comment]
I have not received a reply so far.

**Comment by Zermy** [comment]
Manzil Zaheer`s [Webpage](http://manzil.ml/)

**Comment by jan-christiansen** [comment]
The authors have been contacted, no response yet.
