### ISSUE TITLE
Check references in paper "Syntax Errors" for input processing

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#54]
As discussed we might benefit from checking some of the mentioned references in the syntax errors paper to get other ideas of data processing, specially in terms of input encoding.

**Comment by MadeInGer** [comment]
The article has been created [here](https://github.com/sagr4019/ResearchProject/wiki/Paper-%22Syntax-Errors%22,-Summarization-of-selected-references).

**Comment by jan-christiansen** [comment]
The link is broken

**Comment by jan-christiansen** [comment]
The paper you have selected is probably not the best one because it uses a quite different approach. Next time please read the abstract and the conclusion and check whether the approach is actually connected.
