### ISSUE TITLE
refactor data_generation code and add start parameters

### ISSUE THREAD

**Issue by sagr4019** [sagr4019/ResearchProject#55]
Fix directory errors in the sourcecode of Examples/DataGeneration/data_generation.py
and add start parameters to select amount of valid/invalid programms

**Comment by jan-christiansen** [comment]
I get the following error, when I execute the script.
``` 
 File "data_generation.py", line 112
    os.makedirs(args.out+"/valid")
                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by jan-christiansen** [comment]
* Please use `invalid` instead of `nvalid`, I thought `nvalid` is a typo but it is not.
* The abbreviation for number is no not nr.
* Please use code layout for the invocation example.

**Comment by sagr4019** [comment]
done in commit https://github.com/sagr4019/ResearchProject/commit/dd544270ce2264a51d95d7131ac7a5f6fab5bca9 and https://github.com/sagr4019/ResearchProject/commit/096d715e812a1405a217a8d5abda6aab2e7a83c7
