### ISSUE TITLE
Sequence embedding in "Sequence Classification with LSTM"

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#60]
What kind of sequence embedding is used for the sentiment analysis?

**Comment by MadeInGer** [comment]
They use the standard Keras embedding layer to convert integer of words into a word embedding. 
While using the embedding layer, the word indices (that are returned from the load_data function) are converted to word vectors (word2vec).
Each review is already encoded as a sequence of word indexes (integers) after the dataset has been downloaded - so there is no one-hot encoding needed.
Each review is constrained to be 500 words (shorter reviews are padded) and each word will be mapped as a 32 length vector.
