### ISSUE TITLE
De-Bruijn Encoding

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#65]
Summarise the idea of De Bruijn indices.

**Comment by jan-christiansen** [comment]
Write a short wiki article that explains the basic idea of De Bruijn indices.

**Comment by sagr4019** [comment]
https://github.com/sagr4019/ResearchProject/wiki/De-Bruijn-indices

**Comment by jan-christiansen** [comment]
I have no idea what the sentence "A variable will be displayed as the λ calculus" is supposed to mean. "Eine Variable wird als der Lambda-Kalkül angezeigt".

Please give it another try.
