### ISSUE TITLE
Bug in Toy Language Implementation

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#66]
When I generate a data set using `preprocess_data_string.py` or `preprocess_data_seq_embed.py` and try to train the net I get the following error.
```
ValueError: Input arrays should have the same number of samples as target arrays. Found 6000 input samples and 2400 target samples.
```
In case of `preprocess_data_seq_embed.py` it finds 7200 input samples instead of 6000 but the error is basically the same.

I am using Python 3.6.5, tensor flow 1.8.0, and keras 2.2.0.

**Comment by DanielEggelmann** [comment]
I will implement a change to encode the max_length parameter into the generated training dataset, to make these adjustments unnessecary in the future.

**Comment by DanielEggelmann** [comment]
Change implemented, please download the latest version and see if problems are fixed. The before mentioned changes are then not needed.
