### ISSUE TITLE
Concept for using De-Brujin encoding

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#69]
Develop a concept how the variables in the generated code can we replaced by numbers using a De-Brujin encoding.

**Comment by jan-christiansen** [comment]
First step, provide some example programs and transform them to using De Brujin-indices.

**Comment by DanielEggelmann** [comment]
The concept can be found in the following wiki article:
https://github.com/sagr4019/ResearchProject/wiki/De-Brujin-Indices-in-Toy-Language

**Comment by jan-christiansen** [comment]
Evaluate the concept

**Comment by DanielEggelmann** [comment]
Key points from discussion:
- Usage of De-Brujin Encoding is still questionable, since it makes the neural network obsolete.
- No issues with concept found.

**Comment by jan-christiansen** [comment]
The concept was verified by one of the authors.
