### ISSUE TITLE
Collect forms of static analyses

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#71]
Collect a list of problems that are solved via static analysis. For example, consult the wikipedia article about this topic.

**Comment by MadeInGer** [comment]
An wiki article has been created [here](https://github.com/sagr4019/ResearchProject/wiki/Static-analysis).

**Comment by jan-christiansen** [comment]
The article does not contain "problems that are solved via static analysis". You have listed techniques for implementing static analyses. We will never the less delay this issue in favour of other issues.

**Comment by jan-christiansen** [comment]
We have already decided on a static analysis that we try to implement.
