### ISSUE TITLE
Concept for virtual meetings

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#73]
Propose a solution for a virtual meeting. All participants should be able to use the software, you propose.

**Comment by Zermy** [comment]
For July 19th I would create a Teamviewer meeting. The invitation is sent by e-mail, so that all members can enter via link.

**Comment by Zermy** [comment]
I will open the meeting at 13:45 o'clock. You can join via my invitation or directly with the software. You find the credentials in the invitation mail. Please check your sound and mic.
If you have some troubles please write here.

**Comment by jan-christiansen** [comment]
Worked fine in the first meeting
