### ISSUE TITLE
Read "Building program vector representations for deep learning"

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#74]
Read [Building Program Vector Representations for Deep Learning](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.740.9206&rep=rep1&type=pdf).

**Comment by jan-christiansen** [comment]
Don't write a summary, just prepare a verbal summary for the parts that you did read. Discuss the contents with each other.

**Comment by Zermy** [comment]
All Data and Sourcecode is published here :[link to website] (https://sites.google.com/site/learnrepresent/)
