### ISSUE TITLE
Code request for "Building Program Vector Representations for Deep Learning"

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#79]
Request the code for paper [Building Program Vector Representations for Deep Learning](https://arxiv.org/abs/1409.3358) by writing an email.

**Comment by MadeInGer** [comment]
An email has been sent. I'll write in here when an answer comes in.

**Comment by jan-christiansen** [comment]
This request is obsolete because the code is available at https://sites.google.com/site/learnrepresent/.
