### ISSUE TITLE
explanation of term "min-pooling"

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#9]
Please explain the term above.

**Comment by DanielEggelmann** [comment]
Added wiki page
https://github.com/sagr4019/ResearchProject/wiki/Min-pooling

**Comment by jan-christiansen** [comment]
Please move this article to a general article about pooling that lists different kinds of pooling as well.

**Comment by DanielEggelmann** [comment]
Create wiki article pooling:
https://github.com/sagr4019/ResearchProject/wiki/Pooling

**Comment by jan-christiansen** [comment]
Please move the issue to "Ready for Review", if it is ready for review.
