### ISSUE TITLE
Read Deep Learning for Text  

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#93]
Site: https://freecontent.manning.com/deep-learning-for-text/

**Comment by MadeInGer** [comment]
Here is the link to the second article, which may also be of interest: https://colah.github.io/posts/2014-07-NLP-RNNs-Representations/

**Comment by Zermy** [comment]
In the first article the result is 56% of his test set. I think it's not really usefull for showing efficiency.It would have been interesting wether the result would‘ve been better with more test data.
