### ISSUE TITLE
Check wiki article regarding vanishing and exploding gradient

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#94]
I'll check the wiki article [Vanishing and exploding gradient](https://github.com/sagr4019/ResearchProject/wiki/Vanishing-and-exploding-gradient) and write down comments or additions if anything is unclear.

**Comment by DanielEggelmann** [comment]
I have updated the article with concrete examples / calculations for gradients and the gradient descent method.

**Comment by MadeInGer** [comment]
Thank you for the sample calculations. I guess it's just a question of taste but I would prefer to split the calculations into new line instead of piping them together. However, they have contributed to understanding.

I've got a question.

> This is repeated until a minimum is found.

This means that you continue calculating the points until both values (x, y) are greater than or equal to 0, am I correct?

**Comment by DanielEggelmann** [comment]
The minimum of a function is where its value is the lowest, this does not nessecary mean x and y have to be 0, which is a just a coincidence in the example.
