### ISSUE TITLE
Code Generator for Language as in "A Sound Type System for Secure Flow Analysis"

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#96]
Create an easily expandable code generator for the language used in the paper [A Sound Type System for Secure Flow Analysis](http://users.cis.fiu.edu/~smithg/papers/jcs96.pdf) at point 4 with the exception of "letvar".
Python is preferred.

**Comment by Zermy** [comment]
@MadeInGer Do you understand the right usage of an AST for the data generation?
I try to figure out how we can build the expressions of the paper in an AST. 

An example in C:
https://stackoverflow.com/questions/28719044/how-to-implement-if-else-branch-in-a-abstract-syntax-tree-using-c

**Comment by MadeInGer** [comment]
Not really complete yet. But I've found [a link here](https://msdn.microsoft.com/en-us/magazine/dn818501.aspx) that explains the topic in a good way I think. 

We discussed in our last meeting that it would be better to create a new code generator instead of using our old code to be prepared to code the AST output. I don't think that it is possible to implement AST in our current code. But we are two groups now so feel free to use the old code, maybe I'm wrong.
So I'm still programming a new code generator. Currently it generates code like

`e = 80403154 == t - i + m == -96205293 < 31789504 + b`

This is syntactically correct code according to the rules in the paper. I replaced the comparison-operator `=` by `==` to be able to evaluate the code using python and it evaluates to False if I instantiate the variables, but no one is coding in this way, so I'm not sure how to handle such code fragments and don't know what the AST representation should look like for the code above.

I'll use the next days to do some more research regarding. If you find useful links, you can share them.

**Comment by MadeInGer** [comment]
As discussed in our meeting we want to optimize the code. This will be done in different tickets.
