### ISSUE TITLE
Optimize Code Generator: Limit length of terms

### ISSUE THREAD

**Issue by MadeInGer** [sagr4019/ResearchProject#99]
Limit the depth of terms to avoid running into recursion depth errors. E. g. ten AST levels at most.

**Comment by MadeInGer** [comment]
[The code generator](https://github.com/sagr4019/ResearchProject/tree/master/data-generation-and-validation/security-type-system) has been revised as follows:
### Constraints

- conditions contain identifier on the left side, right side is either an identifier or a number, e. g. `x<y`, `x==y`, `x<2`, `x==2`
- assignments: left side is identifier
- expression sequence is limited to 1, so e. g. x < y is possible, whereas x < y < 2 is impossible
- expression ast: LiteralInt is between -99 and 99 and LiteralStr is a single character (lower/uppercase) to keep the generated code short

Language used is Python 3. Running the program generates at stdout:

1. a phrase, which is either an expression or a command
2. ten random programs with not more than 10 commands per program.

**Comment by jan-christiansen** [comment]
As discussed the generation of expression has to be generalised. Use separate depths for expressions and commands.
